'use client'

import {Urbanist} from "next/font/google";

import Link from "next/link";
import Image from "next/image";

import SearchBar from "@/components/searchbar/searchbar";

// import lightmode from '../../public/images/lightmode.svg';

import styles from "@/app/layout.module.css";

const urbanist = Urbanist({
    weight: "300",
    variable: "--font-urbanist",
    subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${urbanist.variable}`} style={{ margin: "0px" }}>
                <div className={styles.navbar}>
                    <div className={styles.navbar__left}>
                        <Link href={'/'}><h2>Lorechive</h2></Link>
                    </div>
                    <div className={styles.navbar__right}>
                        <SearchBar />
                        {/*<Image src={lightmode} alt={"Light mode"} width="100%" height="100%" />*/}
                        {/*<Image src={darkmode} alt={"Dark mode"} width="100%" height="100%" />*/}
                    </div>
                </div>
                {children}
                <div className={styles.footer}>
                    <div className={styles.footer__row}>
                        <Link href={'/'}><h2>Lorechive</h2></Link>
                        <div className={styles.footer__links}>
                            <h4>Links</h4>
                            <Link href="/">Home</Link>
                        </div>
                    </div>
                    <div>
                        <p>&copy; 2026 Lorechive</p>
                    </div>
                </div>
            </body>
        </html>
    );
}
